"""Writes repo/base/screens/shopping.yaml. The row pool is repetitive, so it is generated."""
N = 20
ROW_H = 38

rows = []
# Written out in full rather than as YAML anchor copies: ESPHome warns on every
# `<<` merge that overrides a key, and each row overrides both id and y.
for i in range(N):
    rows.append(f"""              - label:
                  id: shop_row_{i}
                  hidden: true
                  x: 0
                  y: {i * ROW_H}
                  width: 100%
                  height: {ROW_H}
                  pad_left: 14
                  pad_right: 14
                  pad_top: 8
                  long_mode: DOT
                  recolor: true
                  text: ""
                  text_font: font_shopping
                  text_color: ${{shopping_item_color}}
                  border_side: BOTTOM
                  border_width: 1
                  border_color: ${{shopping_line_color}}
                  gesture_bubble: true""")
rows_yaml = "\n".join(rows)
row_ids = ", ".join(f"id(shop_row_{i})" for i in range(N))

doc = f'''###############################################################################
# Shopping list: a Home Assistant to-do list as a carousel screen.
#
# A thin header bar (cart icon, title, a count in a pill), and under it a
# rounded card with what is still to buy on `shopping_entity`, one row per item,
# each with a small dot in the accent colour and a hairline under it. Past five rows
# the card scrolls with a finger; a thin accent scrollbar runs down its right
# edge and a chevron at the bottom says there is more, until you get there.
# Adding and ticking off stays in Home Assistant (Assist already does "add milk
# to the shopping list" with no help from this file); this screen only shows.
#
#   packages:
#     core:
#       files:
#         - base/core.yaml
#         - base/screens/home.yaml
#         - base/screens/shopping.yaml   # <- a stop on the ring
#   substitutions:
#     shopping_entity: todo.shopping_list
#
# NOTHING TO SET UP IN HOME ASSISTANT beyond the list itself. A to-do entity's
# state is only a count, and its items live behind the `todo.get_items` action,
# so the box asks for them: `homeassistant.action` with `capture_response`,
# which needs "Allow the device to perform Home Assistant actions" on the
# device's page in HA - the same switch the media and thermostat screens need.
# It asks when that count changes (an item added, ticked off or removed) and
# whenever the screen comes into view, which also catches a renamed item.
#
# Also adds a "Show shopping list" button, so Assist can bring the screen up by
# voice the same way base/screens/show-screen.yaml does for the others - a
# button, not a select, for the reason given there.
#
# ROWS ARE A FIXED POOL of {N} labels made at compile time, one widget per row:
# the dot and the name share one label through recolor markup, and the
# hairline is that label's bottom border. Unused rows are hidden, and a hidden
# child does not count towards the card's scroll height, so the card scrolls
# exactly as far as the list goes. Nothing is created or freed at run time -
# internal RAM is what runs short on this board - and a row is only rewritten
# when its text actually changes. Past {N} items the last row reads "+N more".
#
# SWIPES. Horizontal swipes still step the carousel: the card scrolls
# vertically only, so a sideways drag starts no scroll and LVGL hands it on as
# a gesture, bubbled up to the page. There is no full-screen transparent button
# here, unlike base/screens/carousel-example.yaml - it would sit on top of the
# card and swallow the drag that scrolls it.
#
# This file is generated by scripts/gen_shopping.py (the row pool is {N} copies
# of one block, written out in full); edit the script and re-run it rather
# than this file.
###############################################################################
substitutions:
  shopping_entity: todo.shopping_list
  shopping_title: "Shopping list"
  shopping_empty: "Nothing to buy"
  shopping_more: "more"            # the "+3 more" row past the pool
  shopping_bg_color: '0x000000'
  shopping_bar_color: '0x161618'
  shopping_card_color: '0x101012'
  shopping_line_color: '0x2A2A2E'
  shopping_title_color: '0xFFFFFF'
  shopping_muted_color: '0x8A8A8E'
  shopping_item_color: '0xFFFFFF'
  shopping_accent_color: ${{accent_color}}   # icon, dot, pill, scrollbar
  shopping_font_size: '20'

font:
  # Item text, with the three icons it uses folded in, so a row can be one
  # label: the dot before each item, the cart in the header, the chevron.
  - id: font_shopping
    file:
      type: gfonts
      family: ${{font_family}}
      weight: 400
    size: ${{shopping_font_size}}
    glyphsets:
      - ${{font_glyphsets}}
    extras:
      - file:
          type: gfonts
          family: ${{font_family}}
          weight: 400
        glyphs: ${{extra_glyphs}}
      - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf"
        glyphs:
          - "\\U000F09DF"   # circle-small, the dot before each row
          - "\\U000F0110"   # cart, in the header
          - "\\U000F0140"   # chevron-down, "more below"
  # The empty state's one big icon.
  - id: font_shopping_empty
    file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf"
    size: 48
    bpp: 4
    glyphs:
      - "\\U000F0111"   # cart-outline

globals:
  # What each row and the count currently say, so an unchanged list is not
  # redrawn. One string per row, compared before writing.
  - id: shopping_drawn
    type: std::vector<std::string>
    restore_value: false

sensor:
  # The to-do entity's state is the number of items still to do. Any change to
  # it means the list changed, so it is the refresh trigger.
  - platform: homeassistant
    id: shopping_count
    entity_id: ${{shopping_entity}}
    internal: true
    on_value:
      - script.execute: shopping_fetch

button:
  - platform: template
    id: show_shopping_btn
    name: "Show shopping list"
    icon: "mdi:cart"
    on_press:
      - lambda: |-
          id(idle_pos) = 0;
          id(idle_page_idx) = (int) id(page_shopping)->index;
      - script.execute: show_phase_page

script:
  - id: shopping_fetch
    mode: restart
    then:
      - homeassistant.action:
          action: todo.get_items
          data:
            entity_id: ${{shopping_entity}}
            status: needs_action
          capture_response: true
          on_success:
            - lambda: |-
                lv_obj_t *rows[{N}] = {{{row_ids}}};
                auto &drawn = id(shopping_drawn);
                if (drawn.size() != {N} + 1) drawn.assign({N} + 1, std::string("\\x01"));

                // "#RRGGBB text#" colours just the dot; the substitution is
                // 0xRRGGBB, so the prefix comes off.
                const std::string dot = std::string("#") + std::string("${{shopping_accent_color}}").substr(2) +
                                         " \\U000F09DF#  ";
                // Home Assistant wraps every action response as {{"response": ...}},
                // and the device hands that wrapper over as-is.
                JsonArrayConst items =
                    response["response"]["${{shopping_entity}}"]["items"].as<JsonArrayConst>();
                const int total = items.size();
                for (int i = 0; i < {N}; i++) {{
                  std::string text;
                  if (i < total && !(i == {N} - 1 && total > {N})) {{
                    std::string name = items[i]["summary"] | "";
                    // A '#' would end or start a recolor run mid-name.
                    for (char &ch : name) if (ch == '#') ch = ' ';
                    text = dot + name;
                  }} else if (i == {N} - 1 && total > {N}) {{
                    text = std::string("#") + std::string("${{shopping_muted_color}}").substr(2) + " +" +
                           std::to_string(total - ({N} - 1)) + " ${{shopping_more}}#";
                  }}
                  if (text == drawn[i]) continue;
                  drawn[i] = text;
                  if (text.empty()) {{
                    lv_obj_add_flag(rows[i], LV_OBJ_FLAG_HIDDEN);
                  }} else {{
                    lv_label_set_text(rows[i], text.c_str());
                    lv_obj_remove_flag(rows[i], LV_OBJ_FLAG_HIDDEN);
                  }}
                }}

                const std::string count = total ? std::to_string(total) : "";
                if (count != drawn[{N}]) {{
                  drawn[{N}] = count;
                  lv_label_set_text(id(shopping_count_label), count.c_str());
                  if (total) lv_obj_remove_flag(id(shopping_count_label), LV_OBJ_FLAG_HIDDEN);
                  else lv_obj_add_flag(id(shopping_count_label), LV_OBJ_FLAG_HIDDEN);
                }}
                if (total) lv_obj_add_flag(id(shopping_empty_box), LV_OBJ_FLAG_HIDDEN);
                else lv_obj_remove_flag(id(shopping_empty_box), LV_OBJ_FLAG_HIDDEN);
            - script.execute: shopping_more_hint
          on_error:
            - logger.log:
                level: WARN
                format: "Shopping list: todo.get_items failed: %s"
                args: ['error.c_str()']

  # The chevron shows while there is list left below the card's bottom edge.
  # Run after a refresh and when a scroll settles - not on every scroll frame.
  - id: shopping_more_hint
    then:
      - lambda: |-
          lv_obj_t *card = id(shopping_card);
          lv_obj_update_layout(card);
          const bool more = lv_obj_get_scroll_bottom(card) > 4;
          if (more == !lv_obj_has_flag(id(shopping_chevron), LV_OBJ_FLAG_HIDDEN)) return;
          if (more) lv_obj_remove_flag(id(shopping_chevron), LV_OBJ_FLAG_HIDDEN);
          else lv_obj_add_flag(id(shopping_chevron), LV_OBJ_FLAG_HIDDEN);

lvgl:
  pages:
    - id: page_shopping
      skip: false                    # a stop on the carousel
      bg_color: ${{shopping_bg_color}}
      scrollbar_mode: "OFF"
      on_load:
        - script.execute: shopping_fetch
      on_swipe_left:
        - script.execute: idle_swipe_left
      on_swipe_right:
        - script.execute: idle_swipe_right
      widgets:
        # Header bar: cart, title, count pill.
        - obj:
            align: TOP_MID
            width: 320
            height: 34
            radius: 0
            bg_color: ${{shopping_bar_color}}
            bg_opa: COVER
            border_side: BOTTOM
            border_width: 1
            border_color: ${{shopping_line_color}}
            pad_all: 0
            scrollable: false
            gesture_bubble: true
            widgets:
              - label:
                  align: LEFT_MID
                  x: 12
                  text: "\\U000F0110"
                  text_font: font_shopping
                  text_color: ${{shopping_accent_color}}
              - label:
                  align: LEFT_MID
                  x: 40
                  text: "${{shopping_title}}"
                  text_font: font_body
                  text_color: ${{shopping_title_color}}
              - label:
                  id: shopping_count_label
                  hidden: true
                  align: RIGHT_MID
                  x: -10
                  text: ""
                  text_font: font_body
                  text_color: ${{shopping_bg_color}}
                  bg_color: ${{shopping_accent_color}}
                  bg_opa: COVER
                  radius: 10
                  pad_left: 8
                  pad_right: 8
                  pad_top: 1
                  pad_bottom: 1

        # The card the rows scroll in.
        - obj:
            id: shopping_card
            align: TOP_MID
            y: 42
            width: 304
            height: 190
            radius: 12
            bg_color: ${{shopping_card_color}}
            bg_opa: COVER
            border_width: 1
            border_color: ${{shopping_line_color}}
            pad_all: 0
            clip_corner: true
            scroll_dir: VER
            scrollbar_mode: AUTO
            gesture_bubble: true
            scrollbar:
              width: 3
              radius: 2
              pad_right: 3
              pad_top: 8
              pad_bottom: 8
              bg_color: ${{shopping_accent_color}}
              bg_opa: 70%
            on_scroll_end:
              - script.execute: shopping_more_hint
            widgets:
{rows_yaml}

        # Empty state, centred on the card.
        - obj:
            id: shopping_empty_box
            align: TOP_MID
            y: 42
            width: 304
            height: 190
            bg_opa: TRANSP
            border_width: 0
            pad_all: 0
            scrollable: false
            clickable: false
            gesture_bubble: true
            widgets:
              - label:
                  align: CENTER
                  y: -14
                  text: "\\U000F0111"
                  text_font: font_shopping_empty
                  text_color: ${{shopping_line_color}}
              - label:
                  align: CENTER
                  y: 30
                  text: "${{shopping_empty}}"
                  text_font: font_body
                  text_color: ${{shopping_muted_color}}

        # "More below": a small round chip over the card's bottom edge.
        - label:
            id: shopping_chevron
            hidden: true
            align: BOTTOM_MID
            y: -14
            width: 28
            height: 28
            radius: 14
            pad_top: 3
            text_align: CENTER
            text: "\\U000F0140"
            text_font: font_shopping
            text_color: ${{shopping_accent_color}}
            bg_color: ${{shopping_bar_color}}
            bg_opa: COVER
            border_width: 1
            border_color: ${{shopping_line_color}}
            clickable: false
'''
open(__import__('os').path.join(__import__('os').path.dirname(__file__), '..', 'base', 'screens', 'shopping.yaml'), 'w', encoding='utf-8').write(doc)
print('ok')
